/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/_Orders/route'
import { Route as OrderPaymentRouteImport } from './routes/OrderPayment/route'
import { Route as CartRouteImport } from './routes/Cart/route'
import { Route as ProductsParamsIdImport } from './routes/Products/$ParamsId'
import { Route as OrderDetailsRouteImport } from './routes/OrderDetails/_route'
import { Route as OrderDetailsOrderIdImport } from './routes/OrderDetails/$OrderId'
import { Route as OrdersOrdersRouteImport } from './routes/_Orders/Orders/route'

// Create Virtual Routes

const OrderDetailsImport = createFileRoute('/OrderDetails')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const OrderDetailsRoute = OrderDetailsImport.update({
  path: '/OrderDetails',
  getParentRoute: () => rootRoute,
} as any)

const OrdersRouteRoute = OrdersRouteImport.update({
  id: '/_Orders',
  getParentRoute: () => rootRoute,
} as any)

const OrderPaymentRouteRoute = OrderPaymentRouteImport.update({
  path: '/OrderPayment',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/OrderPayment/route.lazy').then((d) => d.Route),
)

const CartRouteRoute = CartRouteImport.update({
  path: '/Cart',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Cart/route.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProductsParamsIdRoute = ProductsParamsIdImport.update({
  path: '/Products/$ParamsId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Products/$ParamsId.lazy').then((d) => d.Route),
)

const OrderDetailsRouteRoute = OrderDetailsRouteImport.update({
  id: '/_route',
  getParentRoute: () => OrderDetailsRoute,
} as any)

const OrderDetailsOrderIdRoute = OrderDetailsOrderIdImport.update({
  path: '/OrderDetails/$OrderId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/OrderDetails/$OrderId.lazy').then((d) => d.Route),
)

const OrdersOrdersRouteRoute = OrdersOrdersRouteImport.update({
  path: '/Orders',
  getParentRoute: () => OrdersRouteRoute,
} as any).lazy(() =>
  import('./routes/_Orders/Orders/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/Cart': {
      id: '/Cart'
      path: '/Cart'
      fullPath: '/Cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRoute
    }
    '/OrderPayment': {
      id: '/OrderPayment'
      path: '/OrderPayment'
      fullPath: '/OrderPayment'
      preLoaderRoute: typeof OrderPaymentRouteImport
      parentRoute: typeof rootRoute
    }
    '/_Orders': {
      id: '/_Orders'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRoute
    }
    '/_Orders/Orders': {
      id: '/_Orders/Orders'
      path: '/Orders'
      fullPath: '/Orders'
      preLoaderRoute: typeof OrdersOrdersRouteImport
      parentRoute: typeof OrdersRouteImport
    }
    '/OrderDetails/$OrderId': {
      id: '/OrderDetails/$OrderId'
      path: '/OrderDetails/$OrderId'
      fullPath: '/OrderDetails/$OrderId'
      preLoaderRoute: typeof OrderDetailsOrderIdImport
      parentRoute: typeof rootRoute
    }
    '/OrderDetails': {
      id: '/OrderDetails'
      path: '/OrderDetails'
      fullPath: '/OrderDetails'
      preLoaderRoute: typeof OrderDetailsImport
      parentRoute: typeof rootRoute
    }
    '/OrderDetails/_route': {
      id: '/OrderDetails/_route'
      path: '/OrderDetails'
      fullPath: '/OrderDetails'
      preLoaderRoute: typeof OrderDetailsRouteImport
      parentRoute: typeof OrderDetailsRoute
    }
    '/Products/$ParamsId': {
      id: '/Products/$ParamsId'
      path: '/Products/$ParamsId'
      fullPath: '/Products/$ParamsId'
      preLoaderRoute: typeof ProductsParamsIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CartRouteRoute,
  OrderPaymentRouteRoute,
  OrdersRouteRoute: OrdersRouteRoute.addChildren({ OrdersOrdersRouteRoute }),
  OrderDetailsOrderIdRoute,
  OrderDetailsRoute: OrderDetailsRoute.addChildren({}),
  ProductsParamsIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Cart",
        "/OrderPayment",
        "/_Orders",
        "/OrderDetails/$OrderId",
        "/OrderDetails",
        "/Products/$ParamsId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/Cart": {
      "filePath": "Cart/route.tsx"
    },
    "/OrderPayment": {
      "filePath": "OrderPayment/route.tsx"
    },
    "/_Orders": {
      "filePath": "_Orders/route.tsx",
      "children": [
        "/_Orders/Orders"
      ]
    },
    "/_Orders/Orders": {
      "filePath": "_Orders/Orders/route.tsx",
      "parent": "/_Orders"
    },
    "/OrderDetails/$OrderId": {
      "filePath": "OrderDetails/$OrderId.tsx"
    },
    "/OrderDetails": {
      "filePath": "OrderDetails",
      "children": [
        "/OrderDetails/_route"
      ]
    },
    "/OrderDetails/_route": {
      "filePath": "OrderDetails/_route.tsx",
      "parent": "/OrderDetails"
    },
    "/Products/$ParamsId": {
      "filePath": "Products/$ParamsId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
